# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        help_text="ID of the actor (user ID, API key ID, or 'system')",
                        max_length=255,
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True, help_text="Email of the actor (if user)", max_length=254
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("user", "User"), ("api_key", "API Key"), ("system", "System")],
                        help_text="Type of actor",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Client user agent")),
                (
                    "request_id",
                    models.CharField(
                        blank=True, help_text="Request ID for correlation", max_length=100
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("api_call", "API Call"),
                            ("permission_change", "Permission Change"),
                            ("settings_change", "Settings Change"),
                            ("billing_event", "Billing Event"),
                            ("session_start", "Session Start"),
                            ("session_end", "Session End"),
                            ("key_created", "API Key Created"),
                            ("key_revoked", "API Key Revoked"),
                            ("key_rotated", "API Key Rotated"),
                        ],
                        help_text="Action performed",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(help_text="Type of resource affected", max_length=100),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, help_text="ID of resource affected", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Human-readable description"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Previous values (for updates)"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="New values (for creates/updates)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional context"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor_id"], name="audit_logs_actor_i_0badd2_idx"),
                    models.Index(fields=["actor_type"], name="audit_logs_actor_t_8f5a74_idx"),
                    models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
                    models.Index(fields=["resource_type"], name="audit_logs_resourc_e11e1b_idx"),
                    models.Index(fields=["resource_id"], name="audit_logs_resourc_5afa9a_idx"),
                    models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
                    models.Index(
                        fields=["tenant", "created_at"], name="audit_logs_tenant__0b1a88_idx"
                    ),
                    models.Index(fields=["tenant", "action"], name="audit_logs_tenant__4c766e_idx"),
                ],
            },
        ),
    ]
