# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("usage_warning", "Usage Warning (80%)"),
                            ("usage_critical", "Usage Critical (90%)"),
                            ("limit_exceeded", "Limit Exceeded"),
                            ("payment_failed", "Payment Failed"),
                            ("subscription_expiring", "Subscription Expiring"),
                        ],
                        help_text="Type of alert",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Alert message")),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Resource type (sessions, tokens, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current usage value",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Threshold value",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False, help_text="Whether alert has been acknowledged"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When alert was acknowledged", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional alert metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "lago_invoice_id",
                    models.CharField(help_text="Lago invoice ID", max_length=255, unique=True),
                ),
                ("invoice_number", models.CharField(help_text="Invoice number", max_length=100)),
                ("amount_cents", models.BigIntegerField(help_text="Total amount in cents")),
                (
                    "taxes_amount_cents",
                    models.BigIntegerField(default=0, help_text="Tax amount in cents"),
                ),
                (
                    "total_amount_cents",
                    models.BigIntegerField(help_text="Total amount including taxes in cents"),
                ),
                (
                    "currency",
                    models.CharField(default="USD", help_text="Currency code", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("paid", "Paid"),
                            ("voided", "Voided"),
                            ("failed", "Payment Failed"),
                        ],
                        default="draft",
                        help_text="Invoice status",
                        max_length=20,
                    ),
                ),
                ("issuing_date", models.DateField(help_text="Invoice issue date")),
                (
                    "payment_due_date",
                    models.DateField(blank=True, help_text="Payment due date", null=True),
                ),
                ("pdf_url", models.URLField(blank=True, help_text="URL to invoice PDF")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional invoice metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-issuing_date"],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session", "Voice Session"),
                            ("api_call", "API Call"),
                            ("audio_minutes", "Audio Minutes"),
                            ("input_tokens", "Input Tokens"),
                            ("output_tokens", "Output Tokens"),
                            ("stt_minutes", "STT Minutes"),
                            ("tts_minutes", "TTS Minutes"),
                        ],
                        help_text="Type of usage event",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, help_text="Quantity of usage", max_digits=20
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="count", help_text="Unit of measurement", max_length=50
                    ),
                ),
                (
                    "lago_event_id",
                    models.CharField(
                        blank=True, help_text="Lago event ID after sync", max_length=255
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, help_text="When event was synced to Lago", null=True
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, help_text="Error message if sync failed"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the usage actually occurred",
                    ),
                ),
            ],
            options={
                "db_table": "usage_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
