# Generated by Django 5.1.4 on 2025-12-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0002_initial"),
        ("billing", "0001_initial"),
        ("projects", "0002_initial"),
        ("sessions", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who acknowledged the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billingalert",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usageevent",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated API key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_events",
                to="api_keys.apikey",
            ),
        ),
        migrations.AddField(
            model_name="usageevent",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_events",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="usageevent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_events",
                to="sessions.session",
            ),
        ),
        migrations.AddField(
            model_name="usageevent",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="billingalert",
            index=models.Index(
                fields=["alert_type"], name="billing_ale_alert_t_76309a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingalert",
            index=models.Index(
                fields=["acknowledged"], name="billing_ale_acknowl_0ba2a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingalert",
            index=models.Index(
                fields=["created_at"], name="billing_ale_created_c397cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingalert",
            index=models.Index(
                fields=["tenant", "acknowledged"], name="billing_ale_tenant__260652_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["lago_invoice_id"], name="invoices_lago_in_f010a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_status_07776b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issuing_date"], name="invoices_issuing_f8c120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "status"], name="invoices_tenant__14414f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["event_type"], name="usage_event_event_t_d2d712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["synced_at"], name="usage_event_synced__531fe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["created_at"], name="usage_event_created_c1f325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["tenant", "event_type"], name="usage_event_tenant__ca50d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="usage_event_tenant__eaf2d8_idx"
            ),
        ),
    ]
