# Generated by Django 5.1.15 on 2025-12-25 05:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import apps.realtime.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.realtime.models.generate_session_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.CharField(default="realtime.session", editable=False, max_length=32),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o-realtime-preview",
                        help_text="Model identifier",
                        max_length=64,
                    ),
                ),
                (
                    "modalities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        default=list,
                        help_text="Enabled modalities",
                        size=None,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, default="", help_text="System prompt / instructions"
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy"),
                            ("ash", "Ash"),
                            ("ballad", "Ballad"),
                            ("coral", "Coral"),
                            ("echo", "Echo"),
                            ("sage", "Sage"),
                            ("shimmer", "Shimmer"),
                            ("verse", "Verse"),
                        ],
                        default="alloy",
                        help_text="Voice for audio output",
                        max_length=32,
                    ),
                ),
                (
                    "input_audio_format",
                    models.CharField(
                        choices=[
                            ("pcm16", "PCM 16-bit (24kHz, mono, little-endian)"),
                            ("g711_ulaw", "G.711 μ-law (8kHz)"),
                            ("g711_alaw", "G.711 A-law (8kHz)"),
                        ],
                        default="pcm16",
                        help_text="Input audio format",
                        max_length=16,
                    ),
                ),
                (
                    "output_audio_format",
                    models.CharField(
                        choices=[
                            ("pcm16", "PCM 16-bit (24kHz, mono, little-endian)"),
                            ("g711_ulaw", "G.711 μ-law (8kHz)"),
                            ("g711_alaw", "G.711 A-law (8kHz)"),
                        ],
                        default="pcm16",
                        help_text="Output audio format",
                        max_length=16,
                    ),
                ),
                (
                    "input_audio_transcription",
                    models.JSONField(
                        blank=True, help_text="Transcription configuration", null=True
                    ),
                ),
                (
                    "turn_detection",
                    models.JSONField(
                        blank=True, help_text="Turn detection configuration", null=True
                    ),
                ),
                ("tools", models.JSONField(default=list, help_text="Function tools")),
                (
                    "tool_choice",
                    models.CharField(default="auto", help_text="Tool choice mode", max_length=64),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.8, help_text="Sampling temperature"),
                ),
                (
                    "max_response_output_tokens",
                    models.CharField(default="inf", help_text="Max output tokens", max_length=16),
                ),
                (
                    "input_audio_noise_reduction",
                    models.JSONField(
                        blank=True, help_text="Noise reduction configuration", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="active",
                        help_text="Session status",
                        max_length=32,
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Session expiration time", null=True
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API key used to create session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realtime_sessions",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realtime_sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EphemeralToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="Token prefix for identification",
                        max_length=16,
                    ),
                ),
                (
                    "session_config",
                    models.JSONField(default=dict, help_text="Pre-configured session settings"),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                (
                    "used",
                    models.BooleanField(default=False, help_text="Whether token has been used"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, help_text="When token was used", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        help_text="API key that created this token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeral_tokens",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Associated tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeral_tokens",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        help_text="Session created with this token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ephemeral_token",
                        to="realtime.realtimesession",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_ephemeral_tokens",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.realtime.models.generate_conversation_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.CharField(
                        default="realtime.conversation", editable=False, max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Parent session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="realtime.realtimesession",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_conversations",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.realtime.models.generate_response_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.CharField(default="realtime.response", editable=False, max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("incomplete", "Incomplete"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        help_text="Response status",
                        max_length=16,
                    ),
                ),
                (
                    "status_details",
                    models.JSONField(blank=True, help_text="Status details", null=True),
                ),
                ("output", models.JSONField(default=list, help_text="Output item IDs")),
                (
                    "usage",
                    models.JSONField(blank=True, help_text="Token usage statistics", null=True),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Response configuration"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="Completion timestamp", null=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Parent session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="realtime.realtimesession",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.realtime.models.generate_item_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.CharField(default="realtime.item", editable=False, max_length=32),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("function_call", "Function Call"),
                            ("function_call_output", "Function Call Output"),
                        ],
                        help_text="Item type",
                        max_length=32,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                        ],
                        help_text="Message role",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("in_progress", "In Progress"),
                        ],
                        default="completed",
                        help_text="Item status",
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(default=list, help_text="Content parts")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Function name (for function_call)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "call_id",
                    models.CharField(
                        blank=True,
                        help_text="Function call ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "arguments",
                    models.TextField(blank=True, help_text="Function arguments JSON", null=True),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Function output (for function_call_output)",
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, help_text="Position in conversation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Parent conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="realtime.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "realtime_conversation_items",
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "position"],
                        name="realtime_co_convers_9fa484_idx",
                    ),
                    models.Index(fields=["type"], name="realtime_co_type_00853f_idx"),
                    models.Index(fields=["call_id"], name="realtime_co_call_id_f00dd8_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="realtimesession",
            index=models.Index(fields=["status"], name="realtime_se_status_20ef56_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimesession",
            index=models.Index(fields=["created_at"], name="realtime_se_created_e4ea85_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimesession",
            index=models.Index(fields=["expires_at"], name="realtime_se_expires_edc7a7_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimesession",
            index=models.Index(fields=["tenant", "status"], name="realtime_se_tenant__2a5841_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimesession",
            index=models.Index(
                fields=["tenant", "created_at"], name="realtime_se_tenant__161beb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ephemeraltoken",
            index=models.Index(fields=["token_hash"], name="realtime_ep_token_h_3b915b_idx"),
        ),
        migrations.AddIndex(
            model_name="ephemeraltoken",
            index=models.Index(fields=["expires_at"], name="realtime_ep_expires_b5f7d3_idx"),
        ),
        migrations.AddIndex(
            model_name="ephemeraltoken",
            index=models.Index(
                fields=["tenant", "expires_at"], name="realtime_ep_tenant__fa7377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["session", "status"], name="realtime_re_session_742337_idx"),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["created_at"], name="realtime_re_created_6be64a_idx"),
        ),
    ]
