# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable email notifications"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable in-app notifications"
                    ),
                ),
                (
                    "billing_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive billing notifications"
                    ),
                ),
                (
                    "security_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive security notifications"
                    ),
                ),
                (
                    "system_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive system notifications"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, help_text="Enable quiet hours"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, help_text="Quiet hours start time", null=True
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="Quiet hours end time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("billing", "Billing"),
                            ("security", "Security"),
                            ("system", "System"),
                        ],
                        default="info",
                        help_text="Notification type",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional data payload"
                    ),
                ),
                ("action_url", models.URLField(blank=True, help_text="Action URL")),
                (
                    "action_label",
                    models.CharField(
                        blank=True, help_text="Action button label", max_length=100
                    ),
                ),
                (
                    "channels",
                    models.JSONField(default=list, help_text="Delivery channels"),
                ),
                (
                    "delivered_at",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Delivery timestamps per channel",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was dismissed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Notification expiration", null=True
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
