# Generated by Django 5.1.15 on 2025-12-25 05:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the project is active"
                    ),
                ),
                (
                    "voice_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Voice agent configuration"
                    ),
                ),
                (
                    "stt_model",
                    models.CharField(
                        default="tiny",
                        help_text="Whisper STT model (tiny, base, small, medium, large)",
                        max_length=100,
                    ),
                ),
                (
                    "stt_language",
                    models.CharField(
                        default="en", help_text="STT language code", max_length=10
                    ),
                ),
                (
                    "tts_model",
                    models.CharField(
                        default="kokoro",
                        help_text="TTS model (kokoro, phoonnx)",
                        max_length=100,
                    ),
                ),
                (
                    "tts_voice",
                    models.CharField(
                        default="af_heart", help_text="TTS voice ID", max_length=100
                    ),
                ),
                (
                    "tts_speed",
                    models.FloatField(
                        default=1.0, help_text="TTS speech speed (0.5-2.0)"
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="groq",
                        help_text="LLM provider (groq, openai)",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="llama-3.3-70b-versatile",
                        help_text="LLM model name",
                        max_length=100,
                    ),
                ),
                (
                    "llm_temperature",
                    models.FloatField(
                        default=0.7, help_text="LLM temperature (0.0-2.0)"
                    ),
                ),
                (
                    "llm_max_tokens",
                    models.PositiveIntegerField(
                        default=1024, help_text="Maximum tokens for LLM response"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt for the voice agent"
                    ),
                ),
                (
                    "turn_detection_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic turn detection"
                    ),
                ),
                (
                    "turn_detection_threshold",
                    models.FloatField(
                        default=0.5,
                        help_text="Turn detection silence threshold (seconds)",
                    ),
                ),
                (
                    "turn_detection_prefix_padding",
                    models.FloatField(
                        default=0.3, help_text="Audio prefix padding (seconds)"
                    ),
                ),
                (
                    "turn_detection_silence_duration",
                    models.FloatField(
                        default=0.5, help_text="Silence duration to end turn (seconds)"
                    ),
                ),
                (
                    "max_session_duration",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Maximum session duration in seconds (default 1 hour)",
                    ),
                ),
                (
                    "max_concurrent_sessions",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum concurrent sessions"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Webhook URL for session events"
                    ),
                ),
                (
                    "webhook_events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of events to send to webhook",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional project settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
