# Generated by Django 5.1.15 on 2025-12-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="projects_slug_25ccba_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["is_active"], name="projects_is_acti_3457d5_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_at"], name="projects_created_40bcd1_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "is_active"], name="projects_tenant__26073d_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_project_slug_per_tenant"
            ),
        ),
    ]
