"""Observability module for AgentVoiceBox.

Provides:
- Prometheus metrics (metrics.py)
- Structured logging (logging.py)
- PII redaction (pii_redaction.py)
"""

from .logging import configure_logging
from .metrics import (
    active_connections,
    active_connections_total,
    auth_attempts_total,
    auth_latency,
    db_connections_active,
    db_query_latency,
    errors_total,
    increment_counter,
    init_metrics,
    llm_generation_latency,
    llm_requests_total,
    llm_tokens_total,
    queue_depth,
    rate_limit_hits_total,
    rate_limit_remaining,
    redis_connections_active,
    redis_operation_latency,
    session_duration_seconds,
    session_starts_total,
    set_gauge,
    stt_audio_duration_seconds,
    stt_requests_total,
    stt_transcription_latency,
    timed,
    track_latency,
    tts_characters_total,
    tts_requests_total,
    tts_synthesis_latency,
    websocket_connections_total,
    websocket_message_latency,
    worker_active,
    worker_utilization,
)
from .pii_redaction import (
    PIIPatterns,
    PIIRedactingFilter,
    PIIRedactor,
    get_redactor,
    redact,
)

__all__ = [
    "configure_logging",
    "init_metrics",
    "websocket_message_latency",
    "websocket_connections_total",
    "active_connections",
    "active_connections_total",
    "session_starts_total",
    "session_duration_seconds",
    "stt_transcription_latency",
    "stt_requests_total",
    "stt_audio_duration_seconds",
    "tts_synthesis_latency",
    "tts_requests_total",
    "tts_characters_total",
    "llm_generation_latency",
    "llm_requests_total",
    "llm_tokens_total",
    "queue_depth",
    "worker_utilization",
    "worker_active",
    "rate_limit_hits_total",
    "rate_limit_remaining",
    "auth_attempts_total",
    "auth_latency",
    "errors_total",
    "db_query_latency",
    "db_connections_active",
    "redis_operation_latency",
    "redis_connections_active",
    "track_latency",
    "timed",
    "increment_counter",
    "set_gauge",
    "PIIPatterns",
    "PIIRedactor",
    "PIIRedactingFilter",
    "get_redactor",
    "redact",
]
