# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Theme name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Theme description")),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1", help_text="Primary color (--eog-primary)", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#8b5cf6",
                        help_text="Secondary color (--eog-secondary)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#06b6d4", help_text="Accent color (--eog-accent)", max_length=7
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#0f172a", help_text="Background color (--eog-bg)", max_length=7
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        default="#1e293b", help_text="Surface color (--eog-surface)", max_length=7
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#f8fafc", help_text="Text color (--eog-text)", max_length=7
                    ),
                ),
                (
                    "text_muted_color",
                    models.CharField(
                        default="#94a3b8",
                        help_text="Muted text color (--eog-text-muted)",
                        max_length=7,
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#334155", help_text="Border color (--eog-border)", max_length=7
                    ),
                ),
                (
                    "success_color",
                    models.CharField(
                        default="#22c55e", help_text="Success color (--eog-success)", max_length=7
                    ),
                ),
                (
                    "warning_color",
                    models.CharField(
                        default="#f59e0b", help_text="Warning color (--eog-warning)", max_length=7
                    ),
                ),
                (
                    "error_color",
                    models.CharField(
                        default="#ef4444", help_text="Error color (--eog-error)", max_length=7
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Inter, system-ui, sans-serif",
                        help_text="Font family",
                        max_length=255,
                    ),
                ),
                (
                    "font_size_base",
                    models.CharField(default="16px", help_text="Base font size", max_length=20),
                ),
                (
                    "border_radius",
                    models.CharField(default="0.5rem", help_text="Border radius", max_length=20),
                ),
                ("custom_css", models.TextField(blank=True, help_text="Additional custom CSS")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the theme is active"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default theme"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "themes",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"), name="unique_theme_name_per_tenant"
                    )
                ],
            },
        ),
    ]
