openapi: 3.1.0
info:
  title: AgentVoiceBox Realtime
  version: 1.0.0
  description: |
    Realtime features are delivered via Django Channels WebSockets.
    See docs/asyncapi.yaml for the WebSocket message contract.

servers:
  - url: http://localhost:65020
    description: Local development

paths: {}
