# Generated by Django 5.1.15 on 2025-12-25 05:50

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="API key name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="API key description"),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 chars for identification (avb_xxxx)",
                        max_length=12,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the full key", max_length=64
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        help_text="API key scopes",
                        size=None,
                    ),
                ),
                (
                    "rate_limit_tier",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (60/min)"),
                            ("elevated", "Elevated (120/min)"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="standard",
                        help_text="Rate limit tier",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Key expiration time", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="Key revocation time", null=True
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, help_text="Reason for revocation"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Last usage time", null=True
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last usage IP address", null=True
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total usage count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
