# Generated by Django 5.1.15 on 2025-12-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who revoked the key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_prefix"], name="api_keys_key_pre_9c2634_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_hash"], name="api_keys_key_has_8f2f29_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["expires_at"], name="api_keys_expires_f68b1a_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["revoked_at"], name="api_keys_revoked_d42b6e_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["created_at"], name="api_keys_created_88dd23_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["tenant", "revoked_at"], name="api_keys_tenant__a34131_idx"),
        ),
    ]
