# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Voice model ID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Voice display name", max_length=255),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("kokoro", "Kokoro"), ("phoonnx", "Phoonnx")],
                        help_text="Voice provider",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Voice language", max_length=10
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, help_text="Voice gender", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Voice description"),
                ),
                (
                    "sample_url",
                    models.URLField(blank=True, help_text="Sample audio URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the voice is available"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "voice_models",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="VoicePersona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Persona name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Persona description"),
                ),
                (
                    "voice_id",
                    models.CharField(
                        default="af_heart", help_text="Kokoro voice ID", max_length=100
                    ),
                ),
                (
                    "voice_speed",
                    models.FloatField(default=1.0, help_text="Voice speed multiplier"),
                ),
                (
                    "stt_model",
                    models.CharField(
                        default="tiny", help_text="Whisper STT model", max_length=100
                    ),
                ),
                (
                    "stt_language",
                    models.CharField(
                        default="en", help_text="STT language code", max_length=10
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="groq", help_text="LLM provider", max_length=50
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="llama-3.3-70b-versatile",
                        help_text="LLM model",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(blank=True, help_text="System prompt for the LLM"),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, help_text="LLM temperature"),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=1024, help_text="Max tokens for LLM response"
                    ),
                ),
                (
                    "turn_detection_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic turn detection"
                    ),
                ),
                (
                    "turn_detection_threshold",
                    models.FloatField(
                        default=0.5, help_text="Turn detection threshold"
                    ),
                ),
                (
                    "silence_duration_ms",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Silence duration for turn detection (ms)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the persona is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default persona"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "voice_personas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="voice_perso_is_acti_6de4f5_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="voice_perso_is_defa_c1a865_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"), name="unique_persona_name_per_tenant"
                    )
                ],
            },
        ),
    ]
