"""
Pydantic Schemas for Session Management API
==========================================

This module defines the Pydantic schemas used for data validation and
serialization in the Session API endpoints. These schemas facilitate the
creation, management, and retrieval of voice interaction sessions and
their associated events and metrics.
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from ninja import Schema


class SessionCreate(Schema):
    """
    Defines the request payload for initiating a new voice interaction session.
    """

    project_id: UUID  # The UUID of the project this session is associated with.
    config: dict[str, Any] = {}  # (Optional) Configuration overrides for the session.
    metadata: dict[str, Any] = (
        {}
    )  # (Optional) Additional, unstructured session metadata.


class SessionResponse(Schema):
    """
    Defines the comprehensive response structure for a single session object.
    This schema provides a detailed view of the session's state, metrics, and metadata.
    """

    id: UUID  # The unique identifier for the session.
    tenant_id: UUID  # The ID of the tenant that owns this session.
    project_id: UUID  # The ID of the project this session belongs to.
    api_key_id: Optional[UUID] = None  # The ID of the API key used, if any.
    user_id: Optional[UUID] = (
        None  # The ID of the user who initiated the session, if authenticated.
    )
    status: str  # The current status of the session (e.g., 'active', 'completed').
    config: dict[str, Any]  # The snapshot of configuration used for this session.
    duration_seconds: float  # The total duration of the session in seconds.
    input_tokens: int  # Total input tokens processed by the LLM.
    output_tokens: int  # Total output tokens generated by the LLM.
    total_tokens: int  # Sum of input and output tokens.
    audio_input_seconds: float  # Total duration of user audio input in seconds.
    audio_output_seconds: (
        float  # Total duration of synthesized audio output in seconds.
    )
    total_audio_seconds: float  # Sum of audio input and output duration.
    turn_count: int  # Number of conversational turns.
    error_code: str  # Error code if the session ended with an error.
    error_message: str  # Detailed error message if the session ended with an error.
    metadata: dict[str, Any]  # Additional session metadata.
    created_at: datetime  # Timestamp of when the session was created.
    started_at: Optional[datetime] = None  # Timestamp when the session became active.
    terminated_at: Optional[datetime] = None  # Timestamp when the session ended.

    @staticmethod
    def from_orm(session) -> "SessionResponse":
        """
        Creates a `SessionResponse` instance from a Django `Session` model instance.

        Args:
            session: The Django `Session` model instance.

        Returns:
            An instance of `SessionResponse`.
        """
        return SessionResponse(
            id=session.id,
            tenant_id=session.tenant_id,
            project_id=session.project_id,
            api_key_id=session.api_key_id,
            user_id=session.user_id,
            status=session.status,
            config=session.config,
            duration_seconds=session.duration_seconds,
            input_tokens=session.input_tokens,
            output_tokens=session.output_tokens,
            total_tokens=session.total_tokens,
            audio_input_seconds=session.audio_input_seconds,
            audio_output_seconds=session.audio_output_seconds,
            total_audio_seconds=session.total_audio_seconds,
            turn_count=session.turn_count,
            error_code=session.error_code,
            error_message=session.error_message,
            metadata=session.metadata,
            created_at=session.created_at,
            started_at=session.started_at,
            terminated_at=session.terminated_at,
        )


class SessionListResponse(Schema):
    """
    Defines the response structure for a paginated list of sessions.
    """

    items: list[SessionResponse]  # The list of sessions on the current page.
    total: int  # The total number of sessions matching the query.
    page: int  # The current page number.
    page_size: int  # The number of items per page.
    pages: int  # The total number of pages.


class SessionEventResponse(Schema):
    """
    Defines the response structure for a single session event.
    """

    id: UUID  # The unique identifier for the event.
    session_id: UUID  # The ID of the session this event belongs to.
    event_type: str  # The type of event (e.g., 'audio.input', 'llm.response').
    data: dict[str, Any]  # Event-specific data payload.
    created_at: datetime  # Timestamp when the event occurred.

    @staticmethod
    def from_orm(event) -> "SessionEventResponse":
        """
        Creates a `SessionEventResponse` instance from a Django `SessionEvent` model instance.

        Args:
            event: The Django `SessionEvent` model instance.

        Returns:
            An instance of `SessionEventResponse`.
        """
        return SessionEventResponse(
            id=event.id,
            session_id=event.session_id,
            event_type=event.event_type,
            data=event.data,
            created_at=event.created_at,
        )


class SessionEventsResponse(Schema):
    """
    Defines the response structure for a list of session events.
    """

    items: list[SessionEventResponse]  # The list of session events.
    total: int  # The total number of events for the session.


class SessionMetricsUpdate(Schema):
    """
    Defines the request payload for updating a session's usage metrics.
    """

    input_tokens: int = 0  # Number of input tokens to add.
    output_tokens: int = 0  # Number of output tokens to add.
    audio_input_seconds: float = 0  # Duration of audio input in seconds to add.
    audio_output_seconds: float = 0  # Duration of audio output in seconds to add.
    increment_turns: bool = False  # If true, increments the turn count by one.


class SessionTerminate(Schema):
    """
    Defines the request payload for terminating a session.
    """

    reason: str = ""  # An optional reason for terminating the session.


class SessionStats(Schema):
    """
    Defines the response structure for aggregated session statistics.
    """

    total_sessions: int  # Total number of sessions.
    active_sessions: int  # Number of sessions currently active.
    completed_sessions: int  # Number of sessions completed normally.
    error_sessions: int  # Number of sessions that ended with an error.
    total_duration_seconds: float  # Sum of all session durations.
    total_input_tokens: int  # Sum of all input tokens across sessions.
    total_output_tokens: int  # Sum of all output tokens across sessions.
    total_audio_input_seconds: float  # Sum of all audio input durations.
    total_audio_output_seconds: float  # Sum of all audio output durations.
    average_duration_seconds: float  # Average duration of sessions.
    average_turns: float  # Average number of turns per session.
