# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantPermissionOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("saas_admin", "SaaS Administrator"),
                            ("tenant_admin", "Tenant Administrator"),
                            ("agent_admin", "Agent Administrator"),
                            ("supervisor", "Supervisor"),
                            ("operator", "Operator"),
                            ("agent_user", "Agent User"),
                            ("viewer", "Viewer"),
                            ("billing_admin", "Billing Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resource", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=30)),
                ("allowed", models.BooleanField()),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Permission Override",
                "verbose_name_plural": "Tenant Permission Overrides",
                "db_table": "tenant_permission_overrides",
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("saas_admin", "SaaS Administrator"),
                            ("tenant_admin", "Tenant Administrator"),
                            ("agent_admin", "Agent Administrator"),
                            ("supervisor", "Supervisor"),
                            ("operator", "Operator"),
                            ("agent_user", "Agent User"),
                            ("viewer", "Viewer"),
                            ("billing_admin", "Billing Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "db_table": "user_role_assignments",
            },
        ),
        migrations.CreateModel(
            name="PermissionMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("saas_admin", "SaaS Administrator"),
                            ("tenant_admin", "Tenant Administrator"),
                            ("agent_admin", "Agent Administrator"),
                            ("supervisor", "Supervisor"),
                            ("operator", "Operator"),
                            ("agent_user", "Agent User"),
                            ("viewer", "Viewer"),
                            ("billing_admin", "Billing Administrator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resource", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=30)),
                ("allowed", models.BooleanField(default=False)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Permission Matrix Entry",
                "verbose_name_plural": "Permission Matrix Entries",
                "db_table": "permission_matrix",
                "indexes": [
                    models.Index(fields=["role"], name="permission__role_34222d_idx"),
                    models.Index(
                        fields=["resource", "action"],
                        name="permission__resourc_e75e4c_idx",
                    ),
                ],
                "unique_together": {("role", "resource", "action")},
            },
        ),
    ]
