# Generated by Django 5.1.4 on 2025-12-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpermissionoverride",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_overrides_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantpermissionoverride",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_overrides",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantpermissionoverride",
            index=models.Index(
                fields=["tenant", "role"], name="tenant_perm_tenant__dc6af5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantpermissionoverride",
            unique_together={("tenant", "role", "resource", "action")},
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["user", "role"], name="user_role_a_user_id_addc9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["tenant", "role"], name="user_role_a_tenant__cf1225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["expires_at"], name="user_role_a_expires_d25c32_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroleassignment",
            unique_together={("tenant", "user", "role")},
        ),
    ]
