# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "keycloak_id",
                    models.CharField(
                        blank=True,
                        help_text="Keycloak user ID (sub claim)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="User email address", max_length=255, unique=True),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, help_text="First name", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, help_text="Last name", max_length=150)),
                ("avatar_url", models.URLField(blank=True, help_text="User avatar URL")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("sysadmin", "System Administrator"),
                            ("admin", "Administrator"),
                            ("developer", "Developer"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                            ("billing", "Billing"),
                        ],
                        default="viewer",
                        help_text="User role within the tenant",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the user account is active"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Whether the user can access Django admin"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True, default=dict, help_text="User preferences and settings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant the user belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["keycloak_id"], name="users_keycloa_655743_idx"),
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(fields=["tenant", "is_active"], name="users_tenant__2f74ee_idx"),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
                ],
            },
        ),
    ]
