# Generated by Django 5.1.15 on 2025-12-25 05:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Activation"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "billing_id",
                    models.CharField(
                        blank=True, help_text="Lago customer ID", max_length=255
                    ),
                ),
                (
                    "keycloak_group_id",
                    models.CharField(
                        blank=True, help_text="Keycloak group ID", max_length=255
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Tenant-specific settings"
                    ),
                ),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("max_projects", models.PositiveIntegerField(default=3)),
                ("max_api_keys", models.PositiveIntegerField(default=10)),
                ("max_sessions_per_month", models.PositiveIntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extended_settings",
                        serialize=False,
                        to="tenants.tenant",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, help_text="Logo URL")),
                ("favicon_url", models.URLField(blank=True, help_text="Favicon URL")),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Primary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#8b5cf6",
                        help_text="Secondary brand color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "default_voice_id",
                    models.CharField(
                        default="af_heart",
                        help_text="Default Kokoro voice ID",
                        max_length=100,
                    ),
                ),
                (
                    "default_stt_model",
                    models.CharField(
                        default="tiny",
                        help_text="Default Whisper STT model",
                        max_length=100,
                    ),
                ),
                (
                    "default_tts_model",
                    models.CharField(
                        default="kokoro", help_text="Default TTS model", max_length=100
                    ),
                ),
                (
                    "default_llm_provider",
                    models.CharField(
                        default="groq", help_text="Default LLM provider", max_length=50
                    ),
                ),
                (
                    "default_llm_model",
                    models.CharField(
                        default="llama-3.3-70b-versatile",
                        help_text="Default LLM model",
                        max_length=100,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Webhook URL for notifications"
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Webhook signing secret (encrypted)",
                        max_length=255,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Enable email notifications"
                    ),
                ),
                (
                    "slack_webhook_url",
                    models.URLField(blank=True, help_text="Slack webhook URL"),
                ),
                (
                    "require_mfa",
                    models.BooleanField(
                        default=False, help_text="Require MFA for all users"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=1440, help_text="Session timeout in minutes"
                    ),
                ),
                (
                    "allowed_ip_ranges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed IP ranges (CIDR notation)",
                    ),
                ),
                (
                    "api_key_expiry_days",
                    models.PositiveIntegerField(
                        default=365, help_text="Default API key expiry in days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "tenant_settings",
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="tenants_status_80d9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["tier"], name="tenants_tier_2ebf51_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["billing_id"], name="tenants_billing_49bf36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["created_at"], name="tenants_created_fc84fe_idx"
            ),
        ),
    ]
