# Generated by Django 5.1.4 on 2025-12-25 20:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0002_initial"),
        ("projects", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("terminated", "Terminated"),
                        ],
                        default="created",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Session configuration snapshot"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Client user agent")),
                (
                    "duration_seconds",
                    models.FloatField(default=0, help_text="Session duration in seconds"),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, help_text="Total input tokens (LLM)"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, help_text="Total output tokens (LLM)"),
                ),
                (
                    "audio_input_seconds",
                    models.FloatField(default=0, help_text="Total audio input duration in seconds"),
                ),
                (
                    "audio_output_seconds",
                    models.FloatField(
                        default=0, help_text="Total audio output duration in seconds"
                    ),
                ),
                (
                    "turn_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of conversation turns"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, help_text="Error code if session ended in error", max_length=100
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if session ended in error"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional session metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When session became active", null=True
                    ),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True, help_text="When session was terminated", null=True
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API key used to create session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created session (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.created", "Session Created"),
                            ("session.started", "Session Started"),
                            ("session.completed", "Session Completed"),
                            ("session.error", "Session Error"),
                            ("session.terminated", "Session Terminated"),
                            ("audio.input", "Audio Input"),
                            ("audio.output", "Audio Output"),
                            ("transcription", "Transcription"),
                            ("llm.request", "LLM Request"),
                            ("llm.response", "LLM Response"),
                            ("tts.request", "TTS Request"),
                            ("tts.response", "TTS Response"),
                            ("turn.start", "Turn Start"),
                            ("turn.end", "Turn End"),
                            ("error", "Error"),
                        ],
                        help_text="Event type",
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Event data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Associated session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="voice_sessions.session",
                    ),
                ),
            ],
            options={
                "db_table": "session_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["status"], name="sessions_status_2c94db_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["project"], name="sessions_project_07f859_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["api_key"], name="sessions_api_key_c4cb38_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["created_at"], name="sessions_created_0a2de2_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["tenant", "status"], name="sessions_tenant__2390ea_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["tenant", "created_at"], name="sessions_tenant__7d867f_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionevent",
            index=models.Index(
                fields=["session", "event_type"], name="session_eve_session_c8af21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionevent",
            index=models.Index(
                fields=["session", "created_at"], name="session_eve_session_445439_idx"
            ),
        ),
    ]
